### ISSUE TITLE
UE 4.27.2 crashes when JSONLiveLink is enabled

### ISSUE THREAD

**Issue by octrow** [justdark/UE_Android_LiveLink#1]
After enabling the plugin in the settings, on restarting UE 4.27.2 crashes with an error:
"The following modules are missing or built with different engine version
JSONLiveLink
Engine modules cannot be compiled at runtime. Please build through your IDE."

**Comment by octrow** [comment]
The error is cured by careful reading of the manual. 
For Windows 11, the plugin is installed in the folder (in my case) "C:\Documents\Unreal Projects\metahuman\Plugins". 
The folder "Plugins" may not be in your project folder, then you can create it manually.

**Comment by Chopin68** [comment]
I also encountered this problem, but I still couldn't solve it, and the following problems occurred
![image](https://user-images.githubusercontent.com/75252160/163539823-59981a2a-4476-43a9-8b34-49f9e8805e36.png)
![image](https://user-images.githubusercontent.com/75252160/163539844-7d6706bd-9c56-4967-8d63-7016fc56b7d6.png)
![image](https://user-images.githubusercontent.com/75252160/163539848-984977f9-77d9-40e5-a163-6329860bd39d.png)
Win11 UE 4.27.2

**Comment by brooks0519** [comment]
the save with @Chopin68 on win10 with UE 4.27.2
