### ISSUE TITLE
No license included

### ISSUE THREAD

**Issue by KeiraTheCat** [justdark/UE_Android_LiveLink#3]
I'm interested in using this as a base for my own project, however there is no license file included.

**Comment by octrow** [comment]
Is it possible to get the source versions from the original repositories?
[https://github.com/ue4plugins/JSONLiveLink/blob/master/LICENSE](https://github.com/ue4plugins/JSONLiveLink/blob/master/LICENSE)
[https://github.com/ue4plugins/JSONLiveLink/blob/master/LICENSE](https://github.com/facemoji/mocap4face/blob/main/LICENSE.md)

**Comment by justdark** [comment]
JSONLiveLink is MIT licence, so you can use the project just follow the mocap4face SDK LICENSE.
