### ISSUE TITLE
头部消失

### ISSUE THREAD

**Issue by putongbing** [justdark/UE_Android_LiveLink#8]
![3](https://user-images.githubusercontent.com/42958100/171534747-b0aba06e-f184-49b9-b6e2-65f200c628f4.png)

**Comment by justdark** [comment]
因为我对head传的transform数据是0，所以你需要把这个pose跟另一个动画相加，再输出到output pose

**Comment by putongbing** [comment]
谢谢，我已经在b站上看了你的评论，现在是工作很好！transform数据是指的mesh自带的位移数据吗？

**Comment by justdark** [comment]
应该是scale数据，放大缩小的

**Comment by justdark** [comment]
另外一个方法是将live link pose的输出和另一个正常的pose相加，这样头的大小也就正常了。close issue
